name: Deploy Service

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Image Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/GeoPropertyServer/geo-property
            git pull
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            pnpm install
            pnpm run build
            systemctl restart geoproperty.service
